# Generated by Django 6.0.3 on 2026-04-20 22:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorial',
            name='editors',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'editor'}, related_name='editorials_as_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='editorial',
            name='journalists',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'journalist'}, related_name='editorials_as_journalist', to=settings.AUTH_USER_MODEL),
        ),
    ]
