# Generated by Django 6.0.3 on 2026-04-20 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_editorial_editors_editorial_journalists'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('articles', models.ManyToManyField(blank=True, related_name='newsletters', to='newsapp.article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletters_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
