# Generated by Django 6.0.3 on 2026-04-21 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsapp", "0005_user_journalist_subscriptions_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="newsletter",
            old_name="description",
            new_name="content",
        ),
        migrations.RemoveField(
            model_name="editorial",
            name="editors",
        ),
        migrations.RemoveField(
            model_name="editorial",
            name="journalists",
        ),
        migrations.RemoveField(
            model_name="newsletter",
            name="articles",
        ),
        migrations.RemoveField(
            model_name="user",
            name="journalist_subscriptions",
        ),
        migrations.RemoveField(
            model_name="user",
            name="publisher_subscriptions",
        ),
        migrations.AddField(
            model_name="article",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="subscribed_journalists",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"role": "journalist"},
                related_name="journalist_subscribers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="subscribed_publishers",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"role": "journalist"},
                related_name="publisher_subscribers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="author",
            field=models.ForeignKey(
                limit_choices_to={"role": "journalist"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="editor",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "editor"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_articles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="author",
            field=models.ForeignKey(
                limit_choices_to={"role": "journalist"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="newsletters",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("reader", "Reader"),
                    ("journalist", "Journalist"),
                    ("editor", "Editor"),
                ],
                max_length=20,
            ),
        ),
    ]
