# Generated by Django 6.0.3 on 2026-04-24 22:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsapp", "0006_rename_description_newsletter_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="editorial",
            name="editors",
            field=models.ManyToManyField(
                limit_choices_to={"role": "editor"},
                related_name="editor_editorials",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="editorial",
            name="journalists",
            field=models.ManyToManyField(
                limit_choices_to={"role": "journalist"},
                related_name="journalist_editorials",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
