# Generated by Django 6.0.3 on 2026-04-24 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsapp", "0007_editorial_editors_editorial_journalists"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletter",
            name="articles",
            field=models.ManyToManyField(
                blank=True, related_name="newsletters", to="newsapp.article"
            ),
        ),
    ]
