# Generated by Django 6.0.3 on 2026-04-28 03:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsapp", "0008_newsletter_articles"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "editor"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_articles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="author",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "journalist"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="editor",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "editor"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="editor_articles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
