# Generated by Django 6.0.3 on 2026-04-28 03:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsapp", "0009_article_approved_by_alter_article_author_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletter",
            name="subscribers",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"role": "reader"},
                related_name="subscribed_newsletters",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
