# Generated by Django 6.0.3 on 2026-04-30 20:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsapp", "0010_newsletter_subscribers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="subscribed_publishers",
        ),
        migrations.AddField(
            model_name="user",
            name="subscribed_editorials",
            field=models.ManyToManyField(
                blank=True, related_name="editorial_subscribers", to="newsapp.editorial"
            ),
        ),
        migrations.AlterField(
            model_name="editorial",
            name="editors",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"role": "editor"},
                related_name="editor_editorials",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="editorial",
            name="journalists",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"role": "journalist"},
                related_name="journalist_editorials",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
